Failure # 1 (occurred at 2024-02-15_08-14-10)
Traceback (most recent call last):
  File "/home/kurukshetra/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 426, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/kurukshetra/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 378, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/kurukshetra/anaconda3/envs/flow/lib/python3.7/site-packages/ray/worker.py", line 1457, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RayOutOfMemoryError): [36mray::PPO.train()[39m (pid=19343, ip=192.168.68.14)
  File "python/ray/_raylet.pyx", line 636, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 619, in ray._raylet.execute_task.function_executor
  File "/home/kurukshetra/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 444, in train
    raise e
  File "/home/kurukshetra/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 433, in train
    result = Trainable.train(self)
  File "/home/kurukshetra/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trainable.py", line 176, in train
    result = self._train()
  File "/home/kurukshetra/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 129, in _train
    fetches = self.optimizer.step()
  File "/home/kurukshetra/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 140, in step
    self.num_envs_per_worker, self.train_batch_size)
  File "/home/kurukshetra/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/optimizers/rollout.py", line 29, in collect_samples
    next_sample = ray_get_and_free(fut_sample)
  File "/home/kurukshetra/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
    result = ray.get(object_ids)
ray.exceptions.RayTaskError(RayOutOfMemoryError): [36mray::RolloutWorker[39m (pid=19337, ip=192.168.68.14)
  File "python/ray/_raylet.pyx", line 627, in ray._raylet.execute_task
  File "/home/kurukshetra/anaconda3/envs/flow/lib/python3.7/site-packages/ray/memory_monitor.py", line 130, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node Kurukshetra is used (55.92 / 58.86 GB). The top 10 memory consumers are:

PID	MEM	COMMAND
1214	6.1GiB	/home/kurukshetra/anaconda3/envs/flow/bin/python3 /home/kurukshetra/anaconda3/envs/flow/bin/tensorbo
19342	1.82GiB	ray::RolloutWorker.sample()
19344	1.79GiB	ray::RolloutWorker.sample()
19337	1.78GiB	ray::RolloutWorker
19341	1.78GiB	ray::RolloutWorker.sample()
19343	0.63GiB	ray::PPO.train()
19236	0.49GiB	python3 train.py multiagent_ring
1303	0.19GiB	/usr/lib/firefox/firefox file:///home/kurukshetra/.local/share/jupyter/runtime/nbserver-1298-open.ht
1642	0.12GiB	/usr/lib/firefox/firefox -contentproc -childID 5 -isForBrowser -prefsLen 29028 -prefMapSize 234398 -
1638	0.12GiB	/usr/lib/firefox/firefox -contentproc -childID 4 -isForBrowser -prefsLen 29028 -prefMapSize 234398 -

In addition, up to 0.28 GiB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray, and the max Redis size with `redis_max_memory`. Note that Ray assumes all system memory is available for use by workers. If your system has other applications running, you should manually set these memory limits to a lower value.

