{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c5551048",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/mnt/c/Users/bpoudel3/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "2023-11-04 13:13:46,254\tWARNING services.py:597 -- setpgrp failed, processes may not be cleaned up properly: [Errno 1] Operation not permitted.\n",
      "2023-11-04 13:13:46,255\tINFO resource_spec.py:216 -- Starting Ray with 18.8 GiB memory available for workers and up to 0.2 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).\n",
      "2023-11-04 13:13:47,075\tINFO ray_trial_executor.py:121 -- Trial PPO_TrafficLightGridBenchmarkEnv-v0_83da5eac: Setting up new remote runner.\n",
      "== Status ==\n",
      "Memory usage on this node: 8.0/31.2 GiB\n",
      "Using FIFO scheduling algorithm.\n",
      "Resources requested: 11/11 CPUs, 0/0 GPUs, 0.0/18.8 GiB heap, 0.0/0.1 GiB objects\n",
      "Result logdir: /home/krishna/ray_results/grid_0\n",
      "Number of trials: 1 (1 RUNNING)\n",
      "+----------------------------------------------+----------+-------+\n",
      "| Trial name                                   | status   | loc   |\n",
      "|----------------------------------------------+----------+-------|\n",
      "| PPO_TrafficLightGridBenchmarkEnv-v0_83da5eac | RUNNING  |       |\n",
      "+----------------------------------------------+----------+-------+\n",
      "\n",
      "\n",
      "\u001b[2m\u001b[36m(pid=18618)\u001b[0m 2023-11-04 13:13:48,040\tINFO trainer.py:371 -- Tip: set 'eager': true or the --eager flag to enable TensorFlow eager execution\n",
      "\u001b[2m\u001b[36m(pid=18618)\u001b[0m 2023-11-04 13:13:49,299\tINFO trainer.py:512 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(pid=18618)\u001b[0m 2023-11-04 13:13:52,284\tWARNING util.py:45 -- Install gputil for GPU system monitoring.\n",
      "\u001b[2m\u001b[36m(pid=18621)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18625)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18619)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18623)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18619)\u001b[0m Could not connect to TraCI server at localhost:42897 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18619)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18624)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18615)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18622)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18617)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18616)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18620)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18621)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18625)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18616)\u001b[0m Could not connect to TraCI server at localhost:51409 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18616)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18620)\u001b[0m Could not connect to TraCI server at localhost:42993 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18620)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18621)\u001b[0m Could not connect to TraCI server at localhost:41153 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18621)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18625)\u001b[0m Could not connect to TraCI server at localhost:52721 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18625)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18616)\u001b[0m Could not connect to TraCI server at localhost:51409 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18616)\u001b[0m  Retrying in 3 seconds\n",
      "\u001b[2m\u001b[36m(pid=18620)\u001b[0m Could not connect to TraCI server at localhost:42993 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18620)\u001b[0m  Retrying in 3 seconds\n",
      "\u001b[2m\u001b[36m(pid=18619)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18621)\u001b[0m Could not connect to TraCI server at localhost:41153 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18621)\u001b[0m  Retrying in 3 seconds\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18625)\u001b[0m Could not connect to TraCI server at localhost:52721 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18625)\u001b[0m  Retrying in 3 seconds\n",
      "\u001b[2m\u001b[36m(pid=18619)\u001b[0m Could not connect to TraCI server at localhost:42897 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18619)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18620)\u001b[0m Could not connect to TraCI server at localhost:42993 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18620)\u001b[0m  Retrying in 4 seconds\n",
      "\u001b[2m\u001b[36m(pid=18616)\u001b[0m Could not connect to TraCI server at localhost:51409 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18616)\u001b[0m  Retrying in 4 seconds\n",
      "\u001b[2m\u001b[36m(pid=18619)\u001b[0m Could not connect to TraCI server at localhost:42897 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18619)\u001b[0m  Retrying in 3 seconds\n",
      "\u001b[2m\u001b[36m(pid=18621)\u001b[0m Could not connect to TraCI server at localhost:41153 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18621)\u001b[0m  Retrying in 4 seconds\n",
      "\u001b[2m\u001b[36m(pid=18625)\u001b[0m Could not connect to TraCI server at localhost:52721 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18625)\u001b[0m  Retrying in 4 seconds\n",
      "\u001b[2m\u001b[36m(pid=18619)\u001b[0m Could not connect to TraCI server at localhost:42897 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18619)\u001b[0m  Retrying in 4 seconds\n",
      "\u001b[2m\u001b[36m(pid=18623)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18624)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18623)\u001b[0m Could not connect to TraCI server at localhost:56191 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18623)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18615)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18617)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18622)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18615)\u001b[0m Could not connect to TraCI server at localhost:33583 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18615)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18617)\u001b[0m Could not connect to TraCI server at localhost:44865 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18617)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18622)\u001b[0m Could not connect to TraCI server at localhost:52727 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18622)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18624)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18624)\u001b[0m Could not connect to TraCI server at localhost:58077 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18624)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18615)\u001b[0m Could not connect to TraCI server at localhost:33583 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18615)\u001b[0m  Retrying in 3 seconds\n",
      "\u001b[2m\u001b[36m(pid=18622)\u001b[0m Could not connect to TraCI server at localhost:52727 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18622)\u001b[0m  Retrying in 3 seconds\n",
      "\u001b[2m\u001b[36m(pid=18623)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18623)\u001b[0m Could not connect to TraCI server at localhost:56191 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18623)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18617)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18624)\u001b[0m Could not connect to TraCI server at localhost:58077 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18624)\u001b[0m  Retrying in 3 seconds\n",
      "\u001b[2m\u001b[36m(pid=18617)\u001b[0m Could not connect to TraCI server at localhost:44865 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18617)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18623)\u001b[0m Could not connect to TraCI server at localhost:56191 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18623)\u001b[0m  Retrying in 3 seconds\n",
      "\u001b[2m\u001b[36m(pid=18615)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18622)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18615)\u001b[0m Could not connect to TraCI server at localhost:33583 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18615)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18622)\u001b[0m Could not connect to TraCI server at localhost:52727 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18622)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18616)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18625)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18621)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18616)\u001b[0m Could not connect to TraCI server at localhost:51409 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18616)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18620)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=18625)\u001b[0m Could not connect to TraCI server at localhost:52721 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18625)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=18621)\u001b[0m Could not connect to TraCI server at localhost:41153 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=18621)\u001b[0m  Retrying in 2 seconds\n",
      "Result for PPO_TrafficLightGridBenchmarkEnv-v0_83da5eac:\n",
      "  custom_metrics: {}\n",
      "  date: 2023-11-04_13-14-27\n",
      "  done: false\n",
      "  episode_len_mean: 800.0\n",
      "  episode_reward_max: 256.1188904351299\n",
      "  episode_reward_mean: 253.44934426475322\n",
      "  episode_reward_min: 251.14399734759886\n",
      "  episodes_this_iter: 9\n",
      "  episodes_total: 9\n",
      "  experiment_id: 93bab0c4a0ce4c67995414b5ab8d56b4\n",
      "  experiment_tag: '0'\n",
      "  hostname: COM2134\n",
      "  info:\n",
      "    grad_time_ms: 772.879\n",
      "    learner:\n",
      "      default_policy:\n",
      "        cur_kl_coeff: 0.20000000298023224\n",
      "        cur_lr: 4.999999873689376e-05\n",
      "        entropy: 12.68542194366455\n",
      "        entropy_coeff: 0.0\n",
      "        kl: 0.005268520675599575\n",
      "        policy_loss: -0.007207025773823261\n",
      "        total_loss: 61.08846664428711\n",
      "        vf_explained_var: -0.0003270064771641046\n",
      "        vf_loss: 61.0946159362793\n",
      "    load_time_ms: 41.889\n",
      "    num_steps_sampled: 8000\n",
      "    num_steps_trained: 7936\n",
      "    sample_time_ms: 33518.688\n",
      "    update_time_ms: 549.78\n",
      "  iterations_since_restore: 1\n",
      "  node_ip: 172.19.177.241\n",
      "  num_healthy_workers: 10\n",
      "  off_policy_estimator: {}\n",
      "  perf:\n",
      "    cpu_util_percent: 14.43\n",
      "    ram_util_percent: 36.82\n",
      "  pid: 18618\n",
      "  policy_reward_max: {}\n",
      "  policy_reward_mean: {}\n",
      "  policy_reward_min: {}\n",
      "  sampler_perf:\n",
      "    mean_env_wait_ms: 21.4149121202949\n",
      "    mean_inference_ms: 0.6225816333242138\n",
      "    mean_processing_ms: 11.012919183846067\n",
      "  time_since_restore: 34.9121618270874\n",
      "  time_this_iter_s: 34.9121618270874\n",
      "  time_total_s: 34.9121618270874\n",
      "  timestamp: 1699118067\n",
      "  timesteps_since_restore: 8000\n",
      "  timesteps_this_iter: 8000\n",
      "  timesteps_total: 8000\n",
      "  training_iteration: 1\n",
      "  trial_id: 83da5eac\n",
      "  \n",
      "== Status ==\n",
      "Memory usage on this node: 12.6/31.2 GiB\n",
      "Using FIFO scheduling algorithm.\n",
      "Resources requested: 11/11 CPUs, 0/0 GPUs, 0.0/18.8 GiB heap, 0.0/0.1 GiB objects\n",
      "Result logdir: /home/krishna/ray_results/grid_0\n",
      "Number of trials: 1 (1 RUNNING)\n",
      "+----------------------------------------------+----------+----------------------+--------+------------------+-------------+----------+\n",
      "| Trial name                                   | status   | loc                  |   iter |   total time (s) |   timesteps |   reward |\n",
      "|----------------------------------------------+----------+----------------------+--------+------------------+-------------+----------|\n",
      "| PPO_TrafficLightGridBenchmarkEnv-v0_83da5eac | RUNNING  | 172.19.177.241:18618 |      1 |          34.9122 |        8000 |  253.449 |\n",
      "+----------------------------------------------+----------+----------------------+--------+------------------+-------------+----------+\n",
      "\n",
      "\n",
      "2023-11-04 13:14:27,513\tERROR trial_runner.py:482 -- Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trial_runner.py\", line 426, in _process_trial\n",
      "    result = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py\", line 378, in fetch_result\n",
      "    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/worker.py\", line 1457, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(FatalTraCIError): \u001b[36mray::PPO.train()\u001b[39m (pid=18618, ip=172.19.177.241)\n",
      "  File \"python/ray/_raylet.pyx\", line 636, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 619, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py\", line 444, in train\n",
      "    raise e\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py\", line 433, in train\n",
      "    result = Trainable.train(self)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trainable.py\", line 176, in train\n",
      "    result = self._train()\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py\", line 129, in _train\n",
      "    fetches = self.optimizer.step()\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py\", line 140, in step\n",
      "    self.num_envs_per_worker, self.train_batch_size)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/optimizers/rollout.py\", line 29, in collect_samples\n",
      "    next_sample = ray_get_and_free(fut_sample)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/utils/memory.py\", line 33, in ray_get_and_free\n",
      "    result = ray.get(object_ids)\n",
      "ray.exceptions.RayTaskError(FatalTraCIError): \u001b[36mray::RolloutWorker.sample()\u001b[39m (pid=18616, ip=172.19.177.241)\n",
      "  File \"python/ray/_raylet.pyx\", line 636, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 619, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 471, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 56, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 99, in get_data\n",
      "    item = next(self.rollout_provider)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 340, in _env_runner\n",
      "    base_env.send_actions(actions_to_send)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/env/base_env.py\", line 332, in send_actions\n",
      "    self.vector_env.vector_step(action_vector)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/env/vector_env.py\", line 110, in vector_step\n",
      "    obs, r, done, info = self.envs[i].step(actions[i])\n",
      "  File \"/mnt/c/Users/bpoudel3/Desktop/flow/flow/envs/base.py\", line 369, in step\n",
      "    self.k.simulation.simulation_step()\n",
      "  File \"/mnt/c/Users/bpoudel3/Desktop/flow/flow/core/kernel/simulation/traci.py\", line 92, in simulation_step\n",
      "    self.kernel_api.simulationStep()\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/traci/connection.py\", line 323, in simulationStep\n",
      "    result = self._sendExact()\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/traci/connection.py\", line 99, in _sendExact\n",
      "    raise FatalTraCIError(\"connection closed by SUMO\")\n",
      "traci.exceptions.FatalTraCIError: connection closed by SUMO\n",
      "2023-11-04 13:14:27,514\tINFO trial_runner.py:530 -- Trial PPO_TrafficLightGridBenchmarkEnv-v0_83da5eac: Attempting to recover trial state from last checkpoint.\n",
      "2023-11-04 13:14:27,517\tINFO ray_trial_executor.py:121 -- Trial PPO_TrafficLightGridBenchmarkEnv-v0_83da5eac: Setting up new remote runner.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=21128)\u001b[0m 2023-11-04 13:14:29,552\tINFO trainer.py:371 -- Tip: set 'eager': true or the --eager flag to enable TensorFlow eager execution\n",
      "\u001b[2m\u001b[36m(pid=21128)\u001b[0m 2023-11-04 13:14:31,772\tINFO trainer.py:512 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(pid=18619)\u001b[0m  Retrying in 1 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/utils/_process_posix.py\", line 162, in system\n",
      "    res_idx = child.expect_list(patterns, self.read_timeout)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/spawnbase.py\", line 372, in expect_list\n",
      "    return exp.expect_loop(timeout)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/expect.py\", line 169, in expect_loop\n",
      "    incoming = spawn.read_nonblocking(spawn.maxread, timeout)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/pty_spawn.py\", line 500, in read_nonblocking\n",
      "    if (timeout != 0) and select(timeout):\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/pty_spawn.py\", line 450, in select\n",
      "    return select_ignore_interrupts([self.child_fd], [], [], timeout)[0]\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/utils.py\", line 143, in select_ignore_interrupts\n",
      "    return select.select(iwtd, owtd, ewtd, timeout)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_13292/3848353481.py\", line 1, in <module>\n",
      "    get_ipython().system('python train.py intersection')\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 633, in system_piped\n",
      "    self.user_ns[\"_exit_code\"] = system(self.var_expand(cmd, depth=1))\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/utils/_process_posix.py\", line 173, in system\n",
      "    child.sendline(chr(3))\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/pty_spawn.py\", line 578, in sendline\n",
      "    return self.send(s + self.linesep)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/pty_spawn.py\", line 563, in send\n",
      "    time.sleep(self.delaybeforesend)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/krishna/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "object of type 'NoneType' has no len()",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/utils/_process_posix.py\u001b[0m in \u001b[0;36msystem\u001b[0;34m(self, cmd)\u001b[0m\n\u001b[1;32m    161\u001b[0m                 \u001b[0;31m# know whether we've finished (if we matched EOF) or not\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 162\u001b[0;31m                 \u001b[0mres_idx\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mchild\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexpect_list\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpatterns\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_timeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    163\u001b[0m                 \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mchild\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbefore\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mout_size\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdecode\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0menc\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'replace'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mend\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m''\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/spawnbase.py\u001b[0m in \u001b[0;36mexpect_list\u001b[0;34m(self, pattern_list, timeout, searchwindowsize, async_, **kw)\u001b[0m\n\u001b[1;32m    371\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 372\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mexp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexpect_loop\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    373\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/expect.py\u001b[0m in \u001b[0;36mexpect_loop\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    168\u001b[0m                 \u001b[0;31m# Still have time left, so read more data\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 169\u001b[0;31m                 \u001b[0mincoming\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mspawn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_nonblocking\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mspawn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmaxread\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    170\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mspawn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdelayafterread\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/pty_spawn.py\u001b[0m in \u001b[0;36mread_nonblocking\u001b[0;34m(self, size, timeout)\u001b[0m\n\u001b[1;32m    499\u001b[0m         \u001b[0;31m# (possibly timeout=None), we call select() with a timeout.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 500\u001b[0;31m         \u001b[0;32mif\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mselect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    501\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0msuper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mspawn\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_nonblocking\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msize\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/pty_spawn.py\u001b[0m in \u001b[0;36mselect\u001b[0;34m(timeout)\u001b[0m\n\u001b[1;32m    449\u001b[0m             \u001b[0;32mdef\u001b[0m \u001b[0mselect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 450\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mselect_ignore_interrupts\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mchild_fd\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    451\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/utils.py\u001b[0m in \u001b[0;36mselect_ignore_interrupts\u001b[0;34m(iwtd, owtd, ewtd, timeout)\u001b[0m\n\u001b[1;32m    142\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 143\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mselect\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mselect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0miwtd\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mowtd\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mewtd\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    144\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mInterruptedError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: ",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "    \u001b[0;31m[... skipping hidden 1 frame]\u001b[0m\n",
      "\u001b[0;32m/tmp/ipykernel_13292/3848353481.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mget_ipython\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msystem\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'python train.py intersection'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/ipykernel/zmqshell.py\u001b[0m in \u001b[0;36msystem_piped\u001b[0;34m(self, cmd)\u001b[0m\n\u001b[1;32m    632\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 633\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0muser_ns\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"_exit_code\"\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0msystem\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvar_expand\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcmd\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdepth\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    634\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/utils/_process_posix.py\u001b[0m in \u001b[0;36msystem\u001b[0;34m(self, cmd)\u001b[0m\n\u001b[1;32m    172\u001b[0m             \u001b[0;31m# curses.ascii.ETX).\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 173\u001b[0;31m             \u001b[0mchild\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msendline\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mchr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    174\u001b[0m             \u001b[0;31m# Read and print any more output the program might produce on its\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/pty_spawn.py\u001b[0m in \u001b[0;36msendline\u001b[0;34m(self, s)\u001b[0m\n\u001b[1;32m    577\u001b[0m         \u001b[0ms\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_coerce_send_string\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0ms\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 578\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0ms\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlinesep\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    579\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/pexpect/pty_spawn.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, s)\u001b[0m\n\u001b[1;32m    562\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdelaybeforesend\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 563\u001b[0;31m             \u001b[0mtime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msleep\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdelaybeforesend\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    564\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: ",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[0;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[1;32m   2098\u001b[0m                         \u001b[0;31m# in the engines. This should return a list of strings.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2099\u001b[0;31m                         \u001b[0mstb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_render_traceback_\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2100\u001b[0m                     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'KeyboardInterrupt' object has no attribute '_render_traceback_'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "    \u001b[0;31m[... skipping hidden 1 frame]\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[0;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[1;32m   2100\u001b[0m                     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2101\u001b[0m                         stb = self.InteractiveTB.structured_traceback(etype,\n\u001b[0;32m-> 2102\u001b[0;31m                                             value, tb, tb_offset=tb_offset)\n\u001b[0m\u001b[1;32m   2103\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2104\u001b[0m                     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_showtraceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0metype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[0;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1366\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1367\u001b[0m         return FormattedTB.structured_traceback(\n\u001b[0;32m-> 1368\u001b[0;31m             self, etype, value, tb, tb_offset, number_of_lines_of_context)\n\u001b[0m\u001b[1;32m   1369\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1370\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[0;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1266\u001b[0m             \u001b[0;31m# Verbose modes need a full traceback\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1267\u001b[0m             return VerboseTB.structured_traceback(\n\u001b[0;32m-> 1268\u001b[0;31m                 \u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0metype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtb_offset\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnumber_of_lines_of_context\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1269\u001b[0m             )\n\u001b[1;32m   1270\u001b[0m         \u001b[0;32melif\u001b[0m \u001b[0mmode\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m'Minimal'\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[0;34m(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1123\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1124\u001b[0m         formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n\u001b[0;32m-> 1125\u001b[0;31m                                                                tb_offset)\n\u001b[0m\u001b[1;32m   1126\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1127\u001b[0m         \u001b[0mcolors\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mColors\u001b[0m  \u001b[0;31m# just a shorthand + quicker name lookup\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mformat_exception_as_a_whole\u001b[0;34m(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)\u001b[0m\n\u001b[1;32m   1080\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1081\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1082\u001b[0;31m         \u001b[0mlast_unique\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrecursion_repeat\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfind_recursion\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0morig_etype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mevalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrecords\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1083\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1084\u001b[0m         \u001b[0mframes\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mformat_records\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrecords\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlast_unique\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrecursion_repeat\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/flow/lib/python3.7/site-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mfind_recursion\u001b[0;34m(etype, value, records)\u001b[0m\n\u001b[1;32m    380\u001b[0m     \u001b[0;31m# first frame (from in to out) that looks different.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    381\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mis_recursion_error\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0metype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrecords\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 382\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrecords\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    383\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    384\u001b[0m     \u001b[0;31m# Select filename, lineno, func_name to track frames with\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: object of type 'NoneType' has no len()"
     ]
    }
   ],
   "source": [
    "!python train.py intersection"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ec3e22f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
